[project]
name = "pynts"
version = "0.1.0"
description = "A light-weight python library to compute tuning scores for neuroscientific data."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scikit-image>=0.25.2",
]
